import 'package:contacts_app/model/contacs_model.dart';

List<ContactsModel> contactsList = [
  ContactsModel(
    id: 1,
    firstName: 'Stefano',
    lastName: 'Alvares',
    number: '12345682',
    image: 'https://randomuser.me/api/portraits/men/75.jpg',
  ),
  ContactsModel(
    id: 2,
    firstName: 'Anastasia',
    email: 'sdafa@gmai.com',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  ),
  ContactsModel(
    id: 3,
    firstName: 'Sarah',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/women/64.jpg',
  ),
  ContactsModel(
    id: 4,
    firstName: 'Florent',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/men/66.jpg',
  ),
  ContactsModel(
    id: 5,
    firstName: 'Florian',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/men/26.jpg',
  ),
  ContactsModel(
    id: 6,
    firstName: 'Stefan',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/men/62.jpg',
  ),
  ContactsModel(
    id: 7,
    firstName: 'Maria',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/women/9.jpg',
  ),
  ContactsModel(
    id: 8,
    firstName: 'Isabelle',
    lastName: 'D.',
    number: '3513122',
    email: 'aaa.aaa.com',
  ),
  ContactsModel(
    id: 9,
    firstName: 'Lewis',
    lastName: 'Hamilton',
    number: '3513122',
  ),
  ContactsModel(
    id: 10,
    firstName: 'Serena',
    lastName: 'Williams',
    number: '3513122',
    email: 'aaa.aaa.com',
  ),
  ContactsModel(
    id: 1,
    firstName: 'Stefano',
    lastName: 'Alvares',
    number: '12345682',
    image: 'https://randomuser.me/api/portraits/men/75.jpg',
  ),
  ContactsModel(
    id: 2,
    firstName: 'Anastasia',
    email: 'sdafa@gmai.com',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  ),
  ContactsModel(
    id: 3,
    firstName: 'Sarah',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/women/64.jpg',
  ),
  ContactsModel(
    id: 4,
    firstName: 'Florent',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/men/66.jpg',
  ),
  ContactsModel(
    id: 5,
    firstName: 'Florian',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/men/26.jpg',
  ),
  ContactsModel(
    id: 6,
    firstName: 'Stefan',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/men/62.jpg',
  ),
  ContactsModel(
    id: 7,
    firstName: 'Maria',
    number: '3513122',
    email: 'aaa.aaa.com',
    image: 'https://randomuser.me/api/portraits/women/9.jpg',
  ),
  ContactsModel(
    id: 8,
    firstName: 'Isabelle',
    lastName: 'D.',
    number: '3513122',
    email: 'aaa.aaa.com',
  ),
  ContactsModel(
    id: 9,
    firstName: 'Lewis',
    lastName: 'Hamilton',
    number: '3513122',
  ),
  ContactsModel(
    id: 10,
    firstName: 'Serena',
    lastName: 'Williams',
    number: '3513122',
    email: 'aaa.aaa.com',
  ),
];
